[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"

[tool.pixi.tasks]
migrate-pytest = { cmd = "python -m refactor migrate-pytest --changed-since development test/", env = { PYTHONPATH = "$HOME/PycharmProjects/refactor:$PYTHONPATH" } }
migrate-pytest-all = { cmd = "python -m refactor migrate-pytest --all test/", env = { PYTHONPATH = "$HOME/PycharmProjects/refactor:$PYTHONPATH" } }
migrate-pytest-dry = { cmd = "python -m refactor migrate-pytest --dry-run --changed-since development test/", env = { PYTHONPATH = "$HOME/PycharmProjects/refactor:$PYTHONPATH" } }

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["setuptools", "wheel", "numpy>=2.2.6", "cython>=3.0.12"]
build-backend = "setuptools.build_meta"

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
combine_as_imports = true
conda_env = "hummingbot"
filter_files = true
skip = ["setup.py"]
