name: "Install environment and Hummingbot"
description: "Installs conda environment, all libraries and compiles Hummingbot"
inputs:
   runner:
     required: true
     description: "Runner to use for the run step"
   conda-env-hash:
     required: true
     description: "Environment file to use"
   conda-inst-hash:
     required: false
     description: "Environment file to use"
     default: "0"
   shell:
     required: false
     description: 'Shell to use for the run step'
     default: bash -l {0}

outputs:
   hb-cache-hit:
     description: "Value of truth regarding the program cache being hit or not"
     value: ${{ steps.program-changes.outputs.cache-hit }}
   conda-cache-hit:
     description: "Value of truth regarding the conda cache being hit or not"
     value: ${{ steps.conda-dependencies.outputs.cache-hit }}
   conda-install-cache-hit:
     description: "Value of truth regarding the conda installation cache being hit or not"
     value: ${{ steps.conda-installation.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - run: echo "$SHELL"
      env:
        SHELL: ${{ inputs.shell }}
      shell: ${{ inputs.shell }}

