name: "Install environment and Hummingbot"
description: "Installs conda environment, all libraries and compiles Hummingbot"
inputs:
   program-cache-hit:
     required: true
     description: "Value of truth regarding the program cache being hit or not"
   dependencies-cache-hit:
     required: true
     description: "Value of truth regarding the program cache being hit or not"
   shell:
     required: true
     description: "Shell to use for the run step"
runs:
  using: "composite"
  steps:
    # Install python/conda to check if core code has changed
    - uses: actions/setup-python@v3
      if: ${{inputs.program-cache-hit}} != 'true' || ${{inputs.dependencies-cache-hit}} != 'true'
      env:
        WITHOUT_CYTHON_OPTIMIZATIONS: 'true'
      with:
        python-version: 3.x

    - uses: pguyot/arm-runner-action@v2
      with:
        image_additional_mb: 2048
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        bind_mount_repository: true
        shell: /bin/bash -eo pipefail
        commands: |
          apt update
          apt install -y wget
          apt-get install build-essential libssl-dev libffi-dev gcc python3-dev python-dev python3 -y
          wget https://github.com/conda-forge/miniforge/releases/download/4.11.0-4/Miniforge3-4.11.0-4-Linux-aarch64.sh
          sh Miniforge3-4.11.0-4-Linux-aarch64.sh -b -p /home/user/miniconda3
          source /home/user/miniconda3/etc/profile.d/conda.sh
          conda init
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda info -a
          conda install -c conda-forge pre_commit
          ./install
          conda info --envs
          conda activate hummingbot
          conda env export
          ./compile
          pre-commit run --files $(git diff --name-only origin/$GITHUB_BASE_REF)
          make test
          make report_coverage
          git fetch --all -q
          git checkout -b $GITHUB_SHA
          coverage xml
          diff-cover --compare-branch=origin/$GITHUB_BASE_REF --fail-under=80 coverage.xml
                
