name: 'Set environment variables'
description: 'Configures environment variables for a workflow'
inputs:
  envFilePath:
    description: 'File path to variable file or directory. Defaults to ./.github/variables/* if none specified and runs against each file in that directory.'
    required: false
    default: ./.github/variables/*
  shell:
    description: 'Shell to use for the run step'
    required: false
    default: bash
runs:
  using: "composite"
  steps:
    - run: |
        sed "/#/d" ${{ inputs.envFilePath }} >> $ENV
      shell: ${{ inputs.shell }}
      env:
        ENV: ${{ github.env.GITHUB_ENV }}