name: ci

on:
  push:
    branches: [master, development, development_unofficial, 'refactor/unit_tests**', 'epic/**']
  pull_request:
    branches: [master, development, development_unofficial, 'refactor/unit_tests**', 'epic/**']
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  run_client:
    name: Check if client files changed
    outputs:
      is_set: ${{ steps.check_files.outputs.is_set }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.+(py|pyx|pyd|yml)
      - name: Check if client files are modified
        id: check_files
        if: env.GIT_DIFF
        run: |
          echo ${{ env.GIT_DIFF }}
          echo "is_set=true" >> $GITHUB_OUTPUT

  build_on_generic_runner:
    name: I/B/T x86 Linux
    needs: run_client
    uses: ./.github/workflows/install_generic_runner.yml
    with:
      should_run: true
  #    should_run: ${{ needs.run_client.outputs.is_set }}
      env-yml-file: setup/environment-linux.yml
      os-matrix: "['ubuntu-latest']"

  build_on_Linux:
    name: I/B/T x86 Linux
    needs: run_client
    uses: ./.github/workflows/install_x86_Linux.yml
    with:
      should_run: true
  #    should_run: ${{ needs.run_client.outputs.is_set }}
      env-yml-file: setup/environment-linux.yml
      os-matrix: "['ubuntu-latest', 'ubuntu-20.04']"

  build_on_macOS:
    name: I/B/T x86 MacOS
    needs: run_client
    uses: ./.github/workflows/install_x86_macOs.yml
    with:
      should_run: true
      #should_run: ${{ needs.run_client.outputs.is_set }}

  build_on_windows:
    name: I/B/T x86 Windows
    needs: run_client
    uses: ./.github/workflows/install_x86_windows.yml
    with:
      should_run: true
      #should_run: ${{ needs.run_client.outputs.is_set }}
  #
  # build_on_arm:
  #   needs: run_client
  #   uses: ./.github/workflows/install_arm_macOS.yml
  #  with:
  #    should_run: ${{ needs.run_client.outputs.is_set }}
  #
  # build_on_WSL:
  #   needs: should_build
  #   uses: ./.github/workflows/install_x86_wsl.yml
  #
